apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod2
  name: testpod2
spec:
  containers:
  - image: nginx:latest
    name: testpod2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
